# Обучение Feedforward Neural Network

In [1]:
import random

import torch
import numpy as np
import torch.nn as nn
import pandas as pd
from torch.utils.data import DataLoader, Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score

SEED = 52

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.backends.mps.is_available():
    torch.mps.manual_seed(SEED)

In [2]:
X_train = pd.read_csv('data/X_train_encoded.csv')
X_test = pd.read_csv('data/X_test_encoded.csv')
y_train = pd.read_csv('data/y_train.csv')
y_test = pd.read_csv('data/y_test.csv')

In [3]:
X_train.head(3)

,age,education.num,capital.gain,capital.loss,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,is_usa_no,is_usa_yes
0,59,14,0,0,40,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1
1,23,9,0,0,40,0,0,1,0,0,...,1,0,0,0,0,0,1,1,0,1
2,57,10,7688,0,45,0,0,1,0,0,...,0,0,0,0,0,0,1,1,0,1

In [4]:
DEVICE = 'cpu'
BATCH_SIZE = 100

## Гипотеза 1
Простая модель с одним скрытым слоем размерности 32

In [5]:
class NeuralNetwork(nn.Module):
    def __init__(self, in_features, hidden_size):
        super().__init__()
        self.l1 = nn.Linear(in_features, hidden_size)
        self.act = nn.ReLU()
        self.outl = nn.Linear(hidden_size, 1)
        self.final_act = nn.Sigmoid()

    def forward(self, x):
        y = self.l1(x)
        y = self.act(y)
        y = self.outl(y)
        y = self.final_act(y)
        return y

In [6]:
model = NeuralNetwork(98, 32)

In [7]:
model.to(DEVICE)

NeuralNetwork(
  (l1): Linear(in_features=98, out_features=32, bias=True)
  (act): ReLU()
  (outl): Linear(in_features=32, out_features=1, bias=True)
  (final_act): Sigmoid()
)

Выделяем валидационную выборку из train

In [8]:
X_train, X_val, y_train , y_val = train_test_split(X_train, y_train, shuffle=True,
                                                    random_state=52, test_size=0.2)

Переносим данные на наш `DEVICE`

In [9]:
X_val.head(3)

,age,education.num,capital.gain,capital.loss,hours.per.week,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,...,relationship_Own-child,relationship_Unmarried,relationship_Wife,race_Asian-Pac-Islander,race_Black,race_Other,race_White,sex_Male,is_usa_no,is_usa_yes
6585,24,13,0,0,40,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,1
17886,23,10,0,0,25,0,0,1,0,0,...,0,0,0,1,0,0,0,1,1,0
24810,20,10,0,0,17,0,0,1,0,0,...,1,0,0,0,0,0,1,0,0,1

In [10]:
y_train

       income
11587       1
15050       0
18563       0
22705       0
24009       0
...       ...
4247        0
24077       0
11019       0
9884        0
23541       0

[20838 rows x 1 columns]

In [11]:
X_train_pt = torch.tensor(X_train.to_numpy()).to(torch.float32).to(DEVICE)
X_test_pt = torch.tensor(X_test.to_numpy()).to(torch.float32).to(DEVICE)
X_val_pt = torch.tensor(X_val.to_numpy()).to(torch.float32).to(DEVICE)
y_train_pt = torch.tensor(y_train.to_numpy()).to(torch.float32).to(DEVICE)
y_test_pt = torch.tensor(y_test.to_numpy()).to(torch.float32).to(DEVICE)
y_val_pt = torch.tensor(y_val.to_numpy()).to(torch.float32).to(DEVICE)

(X_train_pt.shape, X_test_pt.shape, X_val_pt.shape,
 y_train_pt.shape, y_test_pt.shape, y_val_pt.shape)

(torch.Size([20838, 45]),
 torch.Size([6513, 45]),
 torch.Size([5210, 45]),
 torch.Size([20838, 1]),
 torch.Size([6513, 1]),
 torch.Size([5210, 1]))

Создаём DataLoaders, которые будут батчами выдавать данные для обучения нейросети

In [12]:
class AdultDataSet(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __getitem__(self, index):
        return (self.X[index], self.y[index])

    def __len__(self):
        return len(self.X)

In [13]:
train_ds = AdultDataSet(X_train_pt, y_train_pt)
test_ds = AdultDataSet(X_test_pt, y_test_pt)
val_ds = AdultDataSet(X_val_pt, y_val_pt)

In [14]:
def make_loader(ds, shuffle=True, seed=SEED):
    g = torch.Generator().manual_seed(seed)
    return DataLoader(ds, batch_size=BATCH_SIZE, shuffle=shuffle, generator=g)

In [15]:
dl_train = make_loader(train_ds)
dl_val   = make_loader(val_ds)
dl_test  = make_loader(test_ds)

In [16]:
EPOCH_COUNT = 100

Инициализация модели

In [17]:
model = NeuralNetwork(X_train_pt.shape[1], 64).to(DEVICE)
loss_func = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

Обучение

In [18]:
best_val_f1 = -1

for epoch in range(1, EPOCH_COUNT+1):
    model.train()

    for indx, (batch_x, batch_y) in enumerate(iter(dl_train), start=1):
        y_pred = model(batch_x) # [100, 1]
        loss = loss_func(y_pred, batch_y)  # порядок критичен!!!
 
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if indx % 50 == 0:
            y = batch_y.detach().cpu().numpy().astype(np.int64)
            y_pred = y_pred.detach().cpu().numpy()
            y_pred = np.where(y_pred > 0.5, 1, 0)
            f1_train = f1_score(y, y_pred, average='macro')
            print(f'[Train] F1: {f1_train:.4f}')

    model.eval()
    with torch.no_grad():
        f1s = []
        for batch_x, batch_y in dl_val:
            y_pred = model(batch_x)
            y = batch_y.cpu().numpy().astype(np.int64)
            y_pred = y_pred.cpu().numpy()
            y_pred = np.where(y_pred > 0.5, 1, 0)
            f1_val = f1_score(y, y_pred, average='macro')
            f1s.append(f1_val)
        f1_val_mean = torch.tensor(f1s).mean()

        if f1_val_mean > best_val_f1:
            best_val_f1 = f1_val_mean
            torch.save(model.state_dict(), 'models/best_model_weights.pth')

        print('-' * 100)
        print(f'[Val epoch={epoch:2d}] F1: {f1_val_mean:.4f}')
        print('-' * 100)

[Train] F1: 0.2278
[Train] F1: 0.4887
[Train] F1: 0.6533
[Train] F1: 0.6562
----------------------------------------------------------------------------------------------------
[Val epoch= 1] F1: 0.6115
----------------------------------------------------------------------------------------------------
[Train] F1: 0.4902
[Train] F1: 0.6001
[Train] F1: 0.5992
[Train] F1: 0.5464
----------------------------------------------------------------------------------------------------
[Val epoch= 2] F1: 0.6437
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7647
[Train] F1: 0.6686
[Train] F1: 0.6189
[Train] F1: 0.7093
----------------------------------------------------------------------------------------------------
[Val epoch= 3] F1: 0.6380
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5827
[Train] F1: 0.5464
[Train] F1: 0.5556
[Train] F1: 0.6710
----------------------------------------------------------------------------------------------------
[Val epoch= 4] F1: 0.6342
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6426
[Train] F1: 0.6685
[Train] F1: 0.5432
[Train] F1: 0.6572
----------------------------------------------------------------------------------------------------
[Val epoch= 5] F1: 0.6271
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5671
[Train] F1: 0.6165
[Train] F1: 0.5432
[Train] F1: 0.6082
----------------------------------------------------------------------------------------------------
[Val epoch= 6] F1: 0.6237
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6710
[Train] F1: 0.7137
[Train] F1: 0.5932
[Train] F1: 0.7589
----------------------------------------------------------------------------------------------------
[Val epoch= 7] F1: 0.6411
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5657
[Train] F1: 0.6807
[Train] F1: 0.6593
[Train] F1: 0.7217
----------------------------------------------------------------------------------------------------
[Val epoch= 8] F1: 0.5947
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5610
[Train] F1: 0.5924
[Train] F1: 0.5776
[Train] F1: 0.5671
----------------------------------------------------------------------------------------------------
[Val epoch= 9] F1: 0.6318
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5748
[Train] F1: 0.5556
[Train] F1: 0.7165
[Train] F1: 0.5393
----------------------------------------------------------------------------------------------------
[Val epoch=10] F1: 0.6422
----------------------------------------------------------------------------------------------------
[Train] F1: 0.5932
[Train] F1: 0.7080
[Train] F1: 0.6101
[Train] F1: 0.6169
----------------------------------------------------------------------------------------------------
[Val epoch=11] F1: 0.6061
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7782
[Train] F1: 0.5265
[Train] F1: 0.6686
[Train] F1: 0.6779
----------------------------------------------------------------------------------------------------
[Val epoch=12] F1: 0.6827
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6078
[Train] F1: 0.6114
[Train] F1: 0.6656
[Train] F1: 0.6189
----------------------------------------------------------------------------------------------------
[Val epoch=13] F1: 0.6851
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6373
[Train] F1: 0.6262
[Train] F1: 0.6811
[Train] F1: 0.7293
----------------------------------------------------------------------------------------------------
[Val epoch=14] F1: 0.6722
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8371
[Train] F1: 0.6552
[Train] F1: 0.6889
[Train] F1: 0.7508
----------------------------------------------------------------------------------------------------
[Val epoch=15] F1: 0.6968
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6373
[Train] F1: 0.7500
[Train] F1: 0.7401
[Train] F1: 0.6373
----------------------------------------------------------------------------------------------------
[Val epoch=16] F1: 0.7223
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7056
[Train] F1: 0.7611
[Train] F1: 0.7782
[Train] F1: 0.6262
----------------------------------------------------------------------------------------------------
[Val epoch=17] F1: 0.7484
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8192
[Train] F1: 0.7181
[Train] F1: 0.6779
[Train] F1: 0.7500
----------------------------------------------------------------------------------------------------
[Val epoch=18] F1: 0.7368
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6985
[Train] F1: 0.7024
[Train] F1: 0.8282
[Train] F1: 0.7749
----------------------------------------------------------------------------------------------------
[Val epoch=19] F1: 0.7544
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7401
[Train] F1: 0.7812
[Train] F1: 0.7276
[Train] F1: 0.7186
----------------------------------------------------------------------------------------------------
[Val epoch=20] F1: 0.7656
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7424
[Train] F1: 0.8885
[Train] F1: 0.7482
[Train] F1: 0.7759
----------------------------------------------------------------------------------------------------
[Val epoch=21] F1: 0.7590
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7459
[Train] F1: 0.7636
[Train] F1: 0.7914
[Train] F1: 0.7392
----------------------------------------------------------------------------------------------------
[Val epoch=22] F1: 0.7565
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7293
[Train] F1: 0.7702
[Train] F1: 0.7726
[Train] F1: 0.7401
----------------------------------------------------------------------------------------------------
[Val epoch=23] F1: 0.7618
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7812
[Train] F1: 0.7807
[Train] F1: 0.7778
[Train] F1: 0.8442
----------------------------------------------------------------------------------------------------
[Val epoch=24] F1: 0.7628
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7611
[Train] F1: 0.6986
[Train] F1: 0.8119
[Train] F1: 0.8095
----------------------------------------------------------------------------------------------------
[Val epoch=25] F1: 0.7710
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7177
[Train] F1: 0.7932
[Train] F1: 0.7741
[Train] F1: 0.7768
----------------------------------------------------------------------------------------------------
[Val epoch=26] F1: 0.7732
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7378
[Train] F1: 0.7890
[Train] F1: 0.7293
[Train] F1: 0.7086
----------------------------------------------------------------------------------------------------
[Val epoch=27] F1: 0.7645
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7716
[Train] F1: 0.7818
[Train] F1: 0.8400
[Train] F1: 0.6280
----------------------------------------------------------------------------------------------------
[Val epoch=28] F1: 0.7625
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7080
[Train] F1: 0.7533
[Train] F1: 0.7930
[Train] F1: 0.8004
----------------------------------------------------------------------------------------------------
[Val epoch=29] F1: 0.7743
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7519
[Train] F1: 0.8306
[Train] F1: 0.7358
[Train] F1: 0.7967
----------------------------------------------------------------------------------------------------
[Val epoch=30] F1: 0.7624
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7290
[Train] F1: 0.7186
[Train] F1: 0.7669
[Train] F1: 0.7378
----------------------------------------------------------------------------------------------------
[Val epoch=31] F1: 0.7545
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8355
[Train] F1: 0.8619
[Train] F1: 0.8024
[Train] F1: 0.7967
----------------------------------------------------------------------------------------------------
[Val epoch=32] F1: 0.7649
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7741
[Train] F1: 0.7973
[Train] F1: 0.8006
[Train] F1: 0.7600
----------------------------------------------------------------------------------------------------
[Val epoch=33] F1: 0.7676
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8588
[Train] F1: 0.7960
[Train] F1: 0.7563
[Train] F1: 0.7165
----------------------------------------------------------------------------------------------------
[Val epoch=34] F1: 0.7733
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7500
[Train] F1: 0.7702
[Train] F1: 0.8513
[Train] F1: 0.7930
----------------------------------------------------------------------------------------------------
[Val epoch=35] F1: 0.7738
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7500
[Train] F1: 0.7611
[Train] F1: 0.8252
[Train] F1: 0.8192
----------------------------------------------------------------------------------------------------
[Val epoch=36] F1: 0.7679
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7519
[Train] F1: 0.8438
[Train] F1: 0.8513
[Train] F1: 0.7085
----------------------------------------------------------------------------------------------------
[Val epoch=37] F1: 0.7685
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7699
[Train] F1: 0.7726
[Train] F1: 0.7259
[Train] F1: 0.7076
----------------------------------------------------------------------------------------------------
[Val epoch=38] F1: 0.7727
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8552
[Train] F1: 0.7177
[Train] F1: 0.7290
[Train] F1: 0.7500
----------------------------------------------------------------------------------------------------
[Val epoch=39] F1: 0.7796
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7378
[Train] F1: 0.6975
[Train] F1: 0.8313
[Train] F1: 0.8006
----------------------------------------------------------------------------------------------------
[Val epoch=40] F1: 0.7646
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7165
[Train] F1: 0.8016
[Train] F1: 0.7636
[Train] F1: 0.8075
----------------------------------------------------------------------------------------------------
[Val epoch=41] F1: 0.7707
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7930
[Train] F1: 0.7500
[Train] F1: 0.7533
[Train] F1: 0.8667
----------------------------------------------------------------------------------------------------
[Val epoch=42] F1: 0.7842
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7177
[Train] F1: 0.8423
[Train] F1: 0.8095
[Train] F1: 0.7378
----------------------------------------------------------------------------------------------------
[Val epoch=43] F1: 0.7735
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8081
[Train] F1: 0.7276
[Train] F1: 0.8192
[Train] F1: 0.7392
----------------------------------------------------------------------------------------------------
[Val epoch=44] F1: 0.7699
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6621
[Train] F1: 0.7076
[Train] F1: 0.7500
[Train] F1: 0.6802
----------------------------------------------------------------------------------------------------
[Val epoch=45] F1: 0.7773
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8513
[Train] F1: 0.8306
[Train] F1: 0.7669
[Train] F1: 0.8136
----------------------------------------------------------------------------------------------------
[Val epoch=46] F1: 0.7760
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7699
[Train] F1: 0.7763
[Train] F1: 0.7401
[Train] F1: 0.7960
----------------------------------------------------------------------------------------------------
[Val epoch=47] F1: 0.7728
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7930
[Train] F1: 0.7741
[Train] F1: 0.7165
[Train] F1: 0.7924
----------------------------------------------------------------------------------------------------
[Val epoch=48] F1: 0.7835
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7900
[Train] F1: 0.7669
[Train] F1: 0.8493
[Train] F1: 0.7973
----------------------------------------------------------------------------------------------------
[Val epoch=49] F1: 0.7850
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7849
[Train] F1: 0.6974
[Train] F1: 0.8306
[Train] F1: 0.6779
----------------------------------------------------------------------------------------------------
[Val epoch=50] F1: 0.7811
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8024
[Train] F1: 0.7867
[Train] F1: 0.8136
[Train] F1: 0.8243
----------------------------------------------------------------------------------------------------
[Val epoch=51] F1: 0.7666
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8119
[Train] F1: 0.7600
[Train] F1: 0.8567
[Train] F1: 0.8339
----------------------------------------------------------------------------------------------------
[Val epoch=52] F1: 0.7817
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7960
[Train] F1: 0.7818
[Train] F1: 0.8024
[Train] F1: 0.9141
----------------------------------------------------------------------------------------------------
[Val epoch=53] F1: 0.7721
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7024
[Train] F1: 0.7563
[Train] F1: 0.7396
[Train] F1: 0.7669
----------------------------------------------------------------------------------------------------
[Val epoch=54] F1: 0.7783
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8006
[Train] F1: 0.7717
[Train] F1: 0.8125
[Train] F1: 0.8370
----------------------------------------------------------------------------------------------------
[Val epoch=55] F1: 0.7835
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8996
[Train] F1: 0.8423
[Train] F1: 0.7401
[Train] F1: 0.7914
----------------------------------------------------------------------------------------------------
[Val epoch=56] F1: 0.7748
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7967
[Train] F1: 0.8960
[Train] F1: 0.7699
[Train] F1: 0.7812
----------------------------------------------------------------------------------------------------
[Val epoch=57] F1: 0.7789
----------------------------------------------------------------------------------------------------
[Train] F1: 0.6800
[Train] F1: 0.8051
[Train] F1: 0.8400
[Train] F1: 0.8371
----------------------------------------------------------------------------------------------------
[Val epoch=58] F1: 0.7751
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7702
[Train] F1: 0.7807
[Train] F1: 0.8074
[Train] F1: 0.8136
----------------------------------------------------------------------------------------------------
[Val epoch=59] F1: 0.7787
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8192
[Train] F1: 0.8438
[Train] F1: 0.7513
[Train] F1: 0.8588
----------------------------------------------------------------------------------------------------
[Val epoch=60] F1: 0.7803
----------------------------------------------------------------------------------------------------
[Train] F1: 0.8095
[Train] F1: 0.6850
[Train] F1: 0.8125
[Train] F1: 0.8371
----------------------------------------------------------------------------------------------------
[Val epoch=61] F1: 0.7788
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7661
[Train] F1: 0.7914
[Train] F1: 0.6802
[Train] F1: 0.8133
----------------------------------------------------------------------------------------------------
[Val epoch=62] F1: 0.7877
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7293
[Train] F1: 0.8313
[Train] F1: 0.6503
[Train] F1: 0.6017
----------------------------------------------------------------------------------------------------
[Val epoch=63] F1: 0.7882
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7702
[Train] F1: 0.7956
[Train] F1: 0.7921
[Train] F1: 0.7396
----------------------------------------------------------------------------------------------------
[Val epoch=64] F1: 0.7775
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7141
[Train] F1: 0.8371
[Train] F1: 0.7702
[Train] F1: 0.7726
----------------------------------------------------------------------------------------------------
[Val epoch=65] F1: 0.7783
----------------------------------------------------------------------------------------------------
[Train] F1: 0.7288
[Train] F1: 0.8081
[Train] F1: 0.8192
[Train] F1: 0.7600
----------------------------------------------------------------------------------------------------
[Val epoch=66] F1: 0.7879

сохраним модель, показавшую лучший результат на валидационной выборке

In [19]:
model.load_state_dict(
    torch.load('models/best_model_weights.pth', weights_only=True)
)

Проверяем предсказания модели на тесте

In [20]:
# финальный тест

model.eval()

with torch.no_grad():
    ys = []
    preds = []
    for batch_x, batch_y in dl_test:
        y_pred = model(batch_x)
        y = batch_y.cpu().numpy().astype(np.int64)
        y_pred = y_pred.cpu().numpy()
        y_pred = np.where(y_pred > 0.5, 1, 0)
        ys.extend(y.tolist())
        preds.extend(y_pred.tolist())

    f1_nn1 = f1_score(ys, preds, average='macro')
    accuracy_nn1 = accuracy_score(ys, preds)
    precision_nn1 = precision_score(ys, preds)
    recall_nn1 = recall_score(ys, preds)

In [21]:
metrics_nn1 = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_nn1, accuracy_nn1, precision_nn1, recall_nn1]],
    index=['FFNN с одним скрытым слоем']
)

In [22]:
metrics_nn1

                            f1-macro  accuracy  precision    recall
FFNN с одним скрытым слоем   0.79193  0.852602    0.68368  0.675514

## Гипотеза 2
1й скрытый слой будет фича-экстрактором размерности 256, 2й слой - экстрактор фичей более высокого уровня, 3й - так же выходной.

In [23]:
class NeuralNetwork(nn.Module):
    def __init__(self, in_features):
        super().__init__()
        self.l1 = nn.Linear(in_features, 256)
        self.l2 = nn.Linear(256, 64)
        self.l3 = nn.Linear(64, 1)

        self.act = nn.ReLU()
        self.final_act = nn.Sigmoid()

    def forward(self, x):
        y = self.act(self.l1(x))
        y = self.act(self.l2(y))
        y = self.final_act(self.l3(y))
        return y

In [24]:
EPOCH_COUNT = 100

Инициализация модели

In [25]:
model = NeuralNetwork(X_train_pt.shape[1]).to(DEVICE)
loss_func = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

Обучение

In [26]:
best_val_f1 = -1
best_epoch = -1

for epoch in range(1, EPOCH_COUNT+1):
    model.train()

    for indx, (batch_x, batch_y) in enumerate(iter(dl_train), start=1):
        y_pred = model(batch_x) # [100, 1]
        loss = loss_func(y_pred, batch_y)  # порядок критичен!!!
 
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    model.eval()
    with torch.no_grad():
        f1s = []
        for batch_x, batch_y in dl_val:
            y_pred = model(batch_x)
            y = batch_y.cpu().numpy().astype(np.int64)
            y_pred = y_pred.cpu().numpy()
            y_pred = np.where(y_pred > 0.5, 1, 0)
            f1_val = f1_score(y, y_pred, average='macro')
            f1s.append(f1_val)
        f1_val_mean = torch.tensor(f1s).mean()

        if f1_val_mean > best_val_f1:
            best_val_f1 = f1_val_mean
            best_epoch = epoch
            torch.save(model.state_dict(), 'models/best_model_weights.pth')

        print(f'[Val epoch={epoch:2d}] F1: {f1_val_mean:.4f}')

print(f'Best epoch = {best_epoch}')

[Val epoch= 1] F1: 0.6059
[Val epoch= 2] F1: 0.6278
[Val epoch= 3] F1: 0.6349
[Val epoch= 4] F1: 0.6407
[Val epoch= 5] F1: 0.6645
[Val epoch= 6] F1: 0.7176
[Val epoch= 7] F1: 0.7297
[Val epoch= 8] F1: 0.7176
[Val epoch= 9] F1: 0.7004
[Val epoch=10] F1: 0.7565
[Val epoch=11] F1: 0.7229
[Val epoch=12] F1: 0.7409
[Val epoch=13] F1: 0.7342
[Val epoch=14] F1: 0.7516
[Val epoch=15] F1: 0.7569
[Val epoch=16] F1: 0.7336
[Val epoch=17] F1: 0.7543
[Val epoch=18] F1: 0.7437
[Val epoch=19] F1: 0.7553
[Val epoch=20] F1: 0.7564
[Val epoch=21] F1: 0.7611
[Val epoch=22] F1: 0.7377
[Val epoch=23] F1: 0.7382
[Val epoch=24] F1: 0.7333
[Val epoch=25] F1: 0.7355
[Val epoch=26] F1: 0.7510
[Val epoch=27] F1: 0.7658
[Val epoch=28] F1: 0.7537
[Val epoch=29] F1: 0.7831
[Val epoch=30] F1: 0.7548
[Val epoch=31] F1: 0.7692
[Val epoch=32] F1: 0.7338
[Val epoch=33] F1: 0.7716
[Val epoch=34] F1: 0.7648
[Val epoch=35] F1: 0.7735
[Val epoch=36] F1: 0.7774
[Val epoch=37] F1: 0.7801
[Val epoch=38] F1: 0.7737
[Val epoch=39] F1: 0.7499
[Val epoch=40] F1: 0.7717
[Val epoch=41] F1: 0.7846
[Val epoch=42] F1: 0.7765
[Val epoch=43] F1: 0.7375
[Val epoch=44] F1: 0.7846
[Val epoch=45] F1: 0.7355
[Val epoch=46] F1: 0.7552
[Val epoch=47] F1: 0.7220
[Val epoch=48] F1: 0.7748
[Val epoch=49] F1: 0.7789
[Val epoch=50] F1: 0.7880
[Val epoch=51] F1: 0.7725
[Val epoch=52] F1: 0.7848
[Val epoch=53] F1: 0.7888
[Val epoch=54] F1: 0.7752
[Val epoch=55] F1: 0.7707
[Val epoch=56] F1: 0.7655
[Val epoch=57] F1: 0.7814
[Val epoch=58] F1: 0.7613
[Val epoch=59] F1: 0.7868
[Val epoch=60] F1: 0.7876
[Val epoch=61] F1: 0.7565
[Val epoch=62] F1: 0.7738
[Val epoch=63] F1: 0.7483
[Val epoch=64] F1: 0.7778
[Val epoch=65] F1: 0.7806
[Val epoch=66] F1: 0.7842
[Val epoch=67] F1: 0.7562
[Val epoch=68] F1: 0.7590
[Val epoch=69] F1: 0.7832
[Val epoch=70] F1: 0.7607
[Val epoch=71] F1: 0.7718
[Val epoch=72] F1: 0.7636
[Val epoch=73] F1: 0.7804
[Val epoch=74] F1: 0.7739
[Val epoch=75] F1: 0.7642
[Val epoch=76] F1: 0.7845
[Val epoch=77] F1: 0.7646
[Val epoch=78] F1: 0.7764
[Val epoch=79] F1: 0.7674
[Val epoch=80] F1: 0.7807
[Val epoch=81] F1: 0.7797
[Val epoch=82] F1: 0.7906
[Val epoch=83] F1: 0.7861
[Val epoch=84] F1: 0.7914
[Val epoch=85] F1: 0.7899
[Val epoch=86] F1: 0.7873
[Val epoch=87] F1: 0.7909
[Val epoch=88] F1: 0.7717
[Val epoch=89] F1: 0.7836
[Val epoch=90] F1: 0.7880
[Val epoch=91] F1: 0.7792
[Val epoch=92] F1: 0.7334
[Val epoch=93] F1: 0.7285
[Val epoch=94] F1: 0.7930
[Val epoch=95] F1: 0.7745
[Val epoch=96] F1: 0.7868
[Val epoch=97] F1: 0.7940
[Val epoch=98] F1: 0.7827
[Val epoch=99] F1: 0.7731
[Val epoch=100] F1: 0.7606
Best epoch = 97

Сохраняем модель с лучшим результатом на валидационной выборке

In [27]:
model.load_state_dict(
    torch.load('models/best_model_weights.pth', weights_only=True)
)

Проверяем предсказания модели на тесте

In [28]:
# финальный тест

model.eval()

with torch.no_grad():
    ys = []
    preds = []
    for batch_x, batch_y in dl_test:
        y_pred = model(batch_x)
        y = batch_y.cpu().numpy().astype(np.int64)
        y_pred = y_pred.cpu().numpy()
        y_pred = np.where(y_pred > 0.5, 1, 0)
        ys.extend(y.tolist())
        preds.extend(y_pred.tolist())

    f1_nn2 = f1_score(ys, preds, average='macro')
    accuracy_nn2 = accuracy_score(ys, preds)
    precision_nn2 = precision_score(ys, preds)
    recall_nn2 = recall_score(ys, preds)

In [29]:
metrics_nn2 = pd.DataFrame(
    columns=['f1-macro', 'accuracy', 'precision', 'recall'],
    data=[[f1_nn2, accuracy_nn2, precision_nn2, recall_nn2]],
    index=['FFNN с двумя скрытыми слоями']
)

In [30]:
metrics_nn2

                              f1-macro  accuracy  precision   recall
FFNN с двумя скрытыми слоями  0.795231  0.853524   0.680601  0.69144

In [31]:
metrics_all_neural_network = pd.concat([metrics_nn1, metrics_nn2])

In [32]:
metrics_all_neural_network

                              f1-macro  accuracy  precision    recall
FFNN с одним скрытым слоем    0.791930  0.852602   0.683680  0.675514
FFNN с двумя скрытыми слоями  0.795231  0.853524   0.680601  0.691440